### ISSUE TITLE
Enable optimized modules

### ISSUE THREAD

**Issue by dannigt** [quanpn90/NMTGMinor#17]
Hello Quan,

Jan told me about the optimized modules. To use them, should I turn on all of the following, or only a subset? 

```
-fast_xentropy
-fast_xattention
-fast_self_attention
-fast_feed_forward
```

Thanks a lot! And have a nice day!
Danni

**Comment by quanpn90** [comment]
Hello Danni,

I'd recommend the first three. I am still testing the last one and its not that much faster. 

You'd want to compile Apex with these options:

pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" \
 --global-option="--xentropy" \
  --global-option="--fast_multihead_attn" ./

The xentropy is needed for fast entropy. The -fast-multihead_attn can be ignored because the python version is also good.

Quan

**Comment by dannigt** [comment]
Thanks! I'll test the speed-up on our machine somewhen in August. (Sorry I forgot to close the issue earlier!)
